import Footer from "@/components/Footer/Footer"
import Header from "@/components/Header/Header"
import { NextUIProvider } from "@nextui-org/react"
import { Toaster } from "react-hot-toast"
import "./globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <NextUIProvider>
          <main className="main-class">
            {children}
          </main>
        </NextUIProvider>
        <Footer />
        <Toaster toastOptions={{ style: { direction: "ltr" } }} />
      </body>
    </html>
  )
}
